DATA_DIR: '../data'
OUTPUT_DIR: '../models'
PREPROCESSING:
  NORMALIZATION:
    ACTIVE : True
    MINMAX: True
    MEANSTD: False
  NUM_COMPONNENT : 150
  VALID_RATIO : 0.2
  RANDOM_STATE : 21

MODEL_OUTPUT : "output.csv"
