DATA_DIR: '../data'
OUTPUT_DIR: '../models'
PREPROCESSING:
  NORMALIZATION:
    ACTIVE : True
    MINMAX: True
    MEANSTD: False
  NUM_COMPONNENT : 200
  VALID_RATIO : 0.2
  RANDOM_STATE : 21
  BATCH_SIZE : 4
  NUM_THREADS : 4
MODEL_OUTPUT : "RandomForestSubmission.csv"
TENSORBOARD : "./tensorboard"
MODEL:
  SVM:
    ACTIVE : False
    KERNEL: 'rbf'
    DEGREE : 3
    GAMMA: 'scale'
    COEFF0: 0.0
    TOL : 0.001
    C: 1.0
    EPS : 0.2
  RANDOMFOREST :
    ACTIVE : True
    N_ESTIMATOR : 200
    MAX_DEPTH : 100
  LINEAR :
    ACTIVE : False
    NORM : False
  FCN :
    ACTIVE : False
    LR : 0.005
