DATA_DIR: '../data'
OUTPUT_DIR: '../models'
PREPROCESSING:
  NORMALIZATION:
    ACTIVE : False
    MINMAX: False
    MEANSTD: False
  PCA : True
  NUM_COMPONNENT : 60
  VALID_RATIO : 0.2
  RANDOM_STATE : 21
  BATCH_SIZE : 4
  NUM_THREADS : 4
MODEL_OUTPUT : "svm_model.csv"
TENSORBOARD : "./tensorboard"
AVERAGE: ['RandomForestSubmission.csv','SvrGridSearch.csv']
MODEL:
  SVM:
    ACTIVE : True
    KERNEL: 'poly'
    DEGREE : 4
    GAMMA: 'scale'
    COEFF0: 0.0
    TOL : 0.001
    C: 1.0
    EPS : 0.2
    GRID_SEARCH:
      ACTIVE: False
      KERNEL: ["linear", "poly", "rbf", "sigmoid"]
      DEGREE : [1,2,3,4]
      GAMMA: ['scale']
      COEFF0: [0.0,0.1,0.2,0.3]
      TOL : [0.001]
      C: [1.0,2.0,0.5]
      EPS : [0.05,0.1,0.15,0.20]
  RANDOMFOREST :
    ACTIVE : False
    N_ESTIMATOR : 200
    MAX_DEPTH : 100
    GRID_SEARCH:
      ACTIVE: False
      N_ESTIMATOR : [10,200,10]
      MAX_DEPTH : [10,100,10]
  LINEAR :
    ACTIVE : False
    NORM : False
  FCN :
    ACTIVE : False
    LR : 0.005
